### ISSUE TITLE
na_ontap_command does not honor ansible_check_mode

### ISSUE THREAD

**Issue by darksoul42** [ansible-collections/netapp.ontap#102]
### Summary

When using ansible 2.11.2 and netapp.ontap from version 21.7.0, I noticed check_mode is not honored by na_ontap_command.
While I would either expect the command to skip or report that it would run the command, it actually ends up executing it.
This deviation in behavior compared to ansible.builtin.command, for instance, is quite dangerous for unexpecting users.
I had to actually wrap the statement with a "when: not ansible_check_mode" option to ensure I would not shoot myself in the foot.

### Component Name

na_ontap_command

### Ansible Version

```console
$ ansible --version
ansible [core 2.11.2]
  config file = /home/users/xxx/.ansible.cfg
  configured module search path = ['/home/users/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/server_config/lib64/python3.6/site-packages/ansible
  ansible collection location = /home/users/xxx/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/server_config/bin/ansible
  python version = 3.6.3 (default, Apr 10 2019, 14:37:36) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
  jinja version = 2.10.1
  libyaml = True
```

### ONTAP Collection Version

```console
$ ansible-galaxy collection list
[...]
netapp.ontap 21.7.0
```

### ONTAP Version

```console
mycluster::> version
NetApp Release 9.10.1P4: Mon May 09 22:11:44 UTC 2022
```

### Playbook

```console
- name: Suppress automatic case creation
  na_ontap_command:
    hostname: myhostname
    username: myuser
    password: mypass
    https: yes
    validate_certs: no
    command: ['system', 'node', 'autosupport', 'invoke', '-node', '*', '-type', 'all', '-message', 'MAINT=2h']
  delegate_to: localhost
```

### Steps to Reproduce

```yaml (paste below)
- name: Suppress automatic case creation
  na_ontap_command:
    hostname: myhostname
    username: myuser
    password: mypass
    https: yes
    validate_certs: no
    command: ['system', 'node', 'autosupport', 'invoke', '-node', '*', '-type', 'all', '-message', 'MAINT=2h']
  delegate_to: localhost
```

Run with -D -C to run in check mode and output details of execution.

### Expected Results

I expect -C to enable ansible_check_mode, and the command to not actually be executed.

### Actual Results

```console
Even though I am in check mode, the command gets actually executed, and autosupport messages are sent.

I can't paste the output from the actual running environment as it is airgapped.

Looking at the code, the module claims to support check_mode, but has no actual code to react to ansible_check_mode :
- If true, merely display "what it would do"
- If false, actually execute the command
```
