### ISSUE TITLE
Error while creating FC interface

### ISSUE THREAD

**Issue by salvagr** [ansible-collections/netapp.ontap#108]
### Summary

"na_ontap_interface" fails when I try to create a FCP Lif.

### Component Name

na_ontap_interface

### Ansible Version

```console
$ ansible --version
ansible 2.9.27
```

### ONTAP Collection Version

```console
$ ansible-galaxy collection list
```

### ONTAP Version

```console
sridharc-vsim34::> version
NetApp Release 9.10.1
```

### Playbook

```console
- name: create FC interfaces
    na_ontap_interface:
      <<: *login
      state: present
      interface_name: fc01
      interface_type: fc
      home_port: 0a
      home_node: demo-01
      data_protocol: fcp
      vserver: svmfc
```

### Steps to Reproduce

```yaml (paste below)
  collections:
    - netapp.ontap
  vars_files:
    - ./vars/vars.yml
  vars:
    login: &login
      hostname: "{{ ontap_admin_ip }}"
      username: "{{ ontap_admin_username }}"
      password: "{{ ontap_admin_password }}"
      https: "{{ ontap_use_https }}"
      validate_certs: "{{ ontap_validate_certs }}"
  tasks:
  - name: create FC interfaces
    na_ontap_interface:
      <<: *login
      state: present
      interface_name: fc01
      interface_type: fc
      home_port: 0a
      home_node: demo-01
      data_protocol: fcp
      vserver: svmfc
```

### Expected Results

I expected to create a FC lif

### Actual Results

```console
"msg": "Error creating interface fc01: calling: network/fc/interfaces: got {'message': 'Field \"location.home_node.name\" cannot be set in this operation', 'code': '262196', 'target': 'location.home_node.name'}."
```
