### ISSUE TITLE
"hosts: all" + ZAPI Module = Error importing netapp-lib ?

### ISSUE THREAD

**Issue by Posti90** [ansible-collections/netapp.ontap#129]
### Summary

After our latest AWX/Ansible update (21.6.0) some templates do not work anymore and generate error "Error importing netapp-lib or a dependency: No module named 'netapp_lib'. ".

E.g. when modules "na_ontap_debug" or "na_ontap_info" are executed:

Other templates work fine with these modules. After some searching I noticed the following:

Templates do not work with "host: all"
```
- hosts: all
  collections:
    - netapp.ontap
  gather_facts: false
  connection: local
```

Templates work with "host: localhost"
```
- hosts: localhost
  collections:
  - netapp.ontap
  connection: local
  gather_facts: false
```

### Component Name

netapp-lib

### Ansible Version

```console
2.12.5
```

### ONTAP Collection Version

```console
21.23.0
```

### ONTAP Version

```console
9.8 - 9.10
```

### Playbook

```console
---
- hosts: all
  collections:
    - netapp.ontap
  gather_facts: false
  connection: local

  tasks:
  - name: Define creditials for the connection to ONTAP
    set_fact:
      login: &login
        hostname: "{{ xxxx }}"
        username: "{{ xxxx}}"
        password: "{{ xxxx }}"
        https: true
    no_log: true

  - na_ontap_debug:
      <<: *login
```

### Steps to Reproduce

run playbook

### Expected Results

Run playbook with no errors.

### Actual Results

```console
Error importing netapp-lib or a dependency: No module named 'netapp_lib'.  Install the python netapp-lib module or a missing dependency.
```
