### ISSUE TITLE
Allow setting share properties via REST in netapp.ontap.na_ontap_cifs

### ISSUE THREAD

**Issue by robertattenberger** [ansible-collections/netapp.ontap#132]
### Summary

For our fileservice we have to configure some CIFS-Share-Properties that are not set by default, for example "showsnapshot". We would like to do this via the module netapp.ontap.na_ontap_cifs and want like to use the module with REST. This module has for that the parameter "share_properties", but this one is not available for REST. In the REST documentation of Ontap 9.10 I found that share-properties are now available in REST (POST ​/protocols​/cifs​/shares). May you be so kind and make the parameter also available in the ansible module for REST.

Thank you.

### Component Name

netapp.ontap.na_ontap_cifs

### Additional Information

```yaml (paste below)
- name: Create CIFS share
  netapp.ontap.na_ontap_cifs:
    state: present
    name: cifsShareName
    path: /
    vserver: vserverName
    share_properties: browsable,oplocks,showsnapshot
    symlink_properties: read_only,enable
    comment: CIFS share description
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
```
