### ISSUE TITLE
netapp.ontap.na_ontap_user fails with {'message': 'The expression is missing a value', 'code': '262194', 'target': 'owner.name'}

### ISSUE THREAD

**Issue by david-sieg** [ansible-collections/netapp.ontap#140]
### Summary

When I try to create an cluster user on ontap with an empty value for vserver, playbook fails.

### Component Name

na_ontap_user

### Ansible Version

```console
ansible 2.10.17
  config file = /home/ds-admin/ansible/ansible.cfg
  configured module search path = ['/home/ds-admin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ds-admin/.venvs/ansible_2_10/lib64/python3.6/site-packages/ansible
  executable location = /home/ds-admin/.venvs/ansible_2_10/bin/ansible
  python version = 3.6.8 (default, Oct 20 2022, 09:31:56) [GCC 8.5.0 20210514 (Red Hat 8.5.0-15)]
```

### ONTAP Collection Version

```console
Collection            Version
--------------------- -------
netapp.ontap          22.3.0
```

### ONTAP Version

```console
NetApp Release 9.11.1P6: Fri Jan 27 03:16:05 UTC 2023
```

### Playbook

```console
- name: "NetApp | Create NetApp Users"
      netapp.ontap.na_ontap_user:
        state: "{{ user.state | default('present') }}"
        name: "{{ user.name }}"
        applications: "{{ user.application }}"
        authentication_method: "{{ user.authentication_method | default('password') }}"
        set_password: "{{ user.password | default(omit) }}"
        lock_user: "{{ user.locked | default('true') }}"
        role_name: "{{ user.role_name }}"
        vserver: "{{ user.vserver_name }}"
        hostname: "{{ netapp_hostname }}"
        username: "{{ netapp_username }}"
        password: "{{ netapp_password }}"
        https: true
        validate_certs: "{{ validate_certs | default('false') }}"
        use_rest: always
      loop: "{{ netapp_users }}"
      loop_control:
        loop_var: user
```

### Steps to Reproduce

```yaml (paste below)
---

- hosts: localhost
  collections:
    - netapp.ontap
  vars:
    netapp_hostname: 'netappcluster.domain.local'
    netapp_username: 'user'
    netapp_password: 'pass'
    netapp_users:
      - name: trident_user
        password: 'password'
        vserver_name: ""
        application: ontapi
        authentication_method: password
        locked: false
        role_name: trident_role

  tasks:
    - name: "NetApp | Create NetApp Users"
      netapp.ontap.na_ontap_user:
        state: "{{ user.state | default('present') }}"
        name: "{{ user.name }}"
        applications: "{{ user.application }}"
        authentication_method: "{{ user.authentication_method | default('password') }}"
        set_password: "{{ user.password | default(omit) }}"
        lock_user: "{{ user.locked | default('true') }}"
        role_name: "{{ user.role_name }}"
        vserver: "{{ user.vserver_name }}"
        hostname: "{{ netapp_hostname }}"
        username: "{{ netapp_username }}"
        password: "{{ netapp_password }}"
        https: true
        validate_certs: "{{ validate_certs | default('false') }}"
        use_rest: always
      loop: "{{ netapp_users }}"
      loop_control:
        loop_var: user
```

### Expected Results

A user on cluster layer should be created.

### Actual Results

```console
failed: [localhost] (item={'name': 'trident_user', 'password': 'password', 'vserver_name': '', 'application': 'ontapi', 'authentication_method': 'password', 'locked': False, 'role_name': 'trident_role'}) => {
    "ansible_loop_var": "user",
    "changed": false,
    "invocation": {
        "module_args": {
            "application_dicts": null,
            "application_strs": [
                "ontapi"
            ],
            "applications": "ontapi",
            "authentication_method": "password",
            "authentication_password": null,
            "authentication_protocol": null,
            "cert_filepath": null,
            "engine_id": null,
            "feature_flags": null,
            "force_ontap_version": null,
            "hostname": "cluster.domain.local",
            "http_port": null,
            "https": true,
            "key_filepath": null,
            "lock_user": false,
            "name": "trident_user",
            "ontapi": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "privacy_password": null,
            "privacy_protocol": null,
            "remote_switch_ipaddress": null,
            "replace_existing_apps_and_methods": "auto",
            "role_name": "trident_role",
            "set_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "state": "present",
            "use_rest": "always",
            "username": "xnetapp",
            "validate_certs": false,
            "vserver": ""
        }
    },
    "msg": "Error while fetching user info: {'message': 'The expression is missing a value', 'code': '262194', 'target': 'owner.name'}",
    "user": {
        "application": "ontapi",
        "authentication_method": "password",
        "locked": false,
        "name": "trident_user",
        "password": "password",
        "role_name": "trident_role",
        "vserver_name": ""
    }
}
```

**Comment by mohanrajb9** [comment]
To create cluster scoped user in REST, set no value to vserver.
```
- name: Create user test1234 failure test via rest
      na_ontap_user:
        name: test1234
        applications: http,ssh,console
        authentication_method: password
        set_password: password123
        vserver:
        role_name: vsadmin
```

setting vserver: , "" still count as a value.
