### ISSUE TITLE
FSxN - cannot remove file_security_permissions ACL

### ISSUE THREAD

**Issue by PavGregor** [ansible-collections/netapp.ontap#151]
### Summary

Hi, I'm using the `netapp.ontap.na_ontap_file_security_permissions_acl` module to manage a FSxN share. I can add and modify ACLs. However, removing ACLs by setting the state to `absent` does not seem to do anything. The task runs without any errors (reporting no change), but the ACL is not removed.

The below example is trying to remove the default Everyone ACL entry that is created automatically on a new volume, however the same issue exists for other ACL entries, such as AD user accounts.

### Component Name

netapp.ontap.na_ontap_file_security_permissions_acl

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.5.post0]
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.13 (default, Jun 24 2022, 15:27:57) [GCC 8.5.0 20210514 (Red Hat 8.5.0-13)]
  jinja version = 2.11.3
  libyaml = True
```

### ONTAP Collection Version

```console
$ ansible-galaxy collection list
# /usr/share/ansible/collections/ansible_collections
Collection        Version
----------------- -------
amazon.aws        5.2.0
community.crypto  2.8.1
community.general 4.8.1
netapp.ontap      22.4.1
```

### ONTAP Version

```console
fsxn::> version
NetApp Release 9.11.1P6: Fri Jan 27 03:16:05 UTC 2023
```

### Playbook

```console
- name: FSxN create volume and remove Everyone user
  hosts: all
  gather_facts: no

  tasks:
    - name: Create FSxN volume
      netapp.ontap.na_ontap_volume:
        state: present
        name: test
        junction_path: /test
        size: 50
        size_unit: gb
        type: RW
        aggregate_name: aggr1
        volume_security_style: ntfs
        efficiency_policy: auto
        snapshot_policy: default
        tiering_policy: snapshot-only
        tiering_minimum_cooling_days: 2
        vserver: "{{ fsxn_vserver }}"
        hostname: "{{ fsxn_host }}"
        username: fsxadmin
        password: '{{ password }}'
        validate_certs: false
        use_rest: always
        wait_for_completion: true
      delegate_to: localhost

    - name: remove Everyone ACL
      netapp.ontap.na_ontap_file_security_permissions_acl:
        state: absent
        path: /test
        validate_changes: warn
        access_control: file_directory
        access: access_allow
        acl_user: Everyone
        apply_to:
          this_folder: true
          sub_folders: true
          files: true
        vserver: "{{ fsxn_vserver }}"
        hostname: "{{ fsxn_host }}"
        username: fsxadmin
        password: '{{ password }}'
        validate_certs: false
        use_rest: always
      delegate_to: localhost
```

### Steps to Reproduce

Run the above playbook to create a new volume on the FSxN file system and attempt to remove the default Everyone ACL entry.

### Expected Results

The Everyone ACL should be removed from the volume.

### Actual Results

```console
fsxn::> vserver security file-directory show -vserver vserver -path /test

                Vserver: vserver
              File Path: /test
      File Inode Number: 64
         Security Style: ntfs
        Effective Style: ntfs
         DOS Attributes: 10
 DOS Attributes in Text: ----D---
Expanded Dos Attributes: -
           UNIX User Id: 0
          UNIX Group Id: 0
         UNIX Mode Bits: 777
 UNIX Mode Bits in Text: rwxrwxrwx
                   ACLs: NTFS Security Descriptor
                         Control:0x8004
                         Owner:BUILTIN\Administrators
                         Group:BUILTIN\Administrators
                         DACL - ACEs
                           ALLOW-Everyone-0x1f01ff
                           ALLOW-Everyone-0x10000000-OI|CI|IO
```

**Comment by mohanrajb9** [comment]
REST API only supports bulk deletion of SLAG acls.
to delete file-directory acl, we need to set values for acl_user, apply_to, access that matches with one of current file directory acls.

I tried your tasks, there are 2 acls created in the path /test, so we need 2 tasks to remove both acl. the difference is in apply_to.

```
- name: remove Everyone ACL
      netapp.ontap.na_ontap_file_security_permissions_acl:
        state: absent
        path: /test
        validate_changes: warn
        access_control: file_directory
        access: access_allow
        acl_user: Everyone
        apply_to:
          this_folder: true
        vserver: "{{ fsxn_vserver }}"
        hostname: "{{ fsxn_host }}"
        username: fsxadmin
        password: '{{ password }}'
        validate_certs: false
        use_rest: always
    
    - name: remove Everyone ACL2
      netapp.ontap.na_ontap_file_security_permissions_acl:
        state: absent
        path: /test
        validate_changes: warn
        access_control: file_directory
        access: access_allow
        acl_user: Everyone
        apply_to:
          sub_folders: true
          files: true
        vserver: "{{ fsxn_vserver }}"
        hostname: "{{ fsxn_host }}"
        username: fsxadmin
        password: '{{ password }}'
        validate_certs: false
        use_rest: always
```

**Comment by PavGregor** [comment]
ok thanks @mohanrajb9 your example of removing the default Everyone ACL entry using the two ACL tasks does work for me.

However, would you expect the following to also work (same `acl_user`, `apply_to`, `access`)?

```
- name: ADD ACL user
  netapp.ontap.na_ontap_file_security_permissions_acl:
    state: present
    path: /{{ fsxn_share_name }}
    acl_user: AD-USER
    access_control: file_directory
    access: access_allow
    rights: full_control
    apply_to:
      this_folder: true
      sub_folders: true
      files: true
    validate_changes: warn
    hostname: "{{ fsxn_host }}"
    vserver: "{{ fsxn_vserver }}"
    username: fsxadmin
    password: "{{ fsxn_password }}"
    validate_certs: false
    use_rest: always
  delegate_to: localhost

- name: Sleep for 5s
  ansible.builtin.wait_for:
    timeout: 5
  delegate_to: localhost

- name: REMOVE ACL user
  netapp.ontap.na_ontap_file_security_permissions_acl:
    state: absent
    path: /{{ fsxn_share_name }}
    acl_user: AD-USER
    access_control: file_directory
    access: access_allow
    apply_to:
      this_folder: true
      sub_folders: true
      files: true
    validate_changes: warn
    hostname: "{{ fsxn_host }}"
    vserver: "{{ fsxn_vserver }}"
    username: fsxadmin
    password: "{{ fsxn_password }}"
    validate_certs: false
    use_rest: always
  delegate_to: localhost
```
This does not work for me, the user ACL is not removed:
```
FsxN::> vserver security file-directory show -vserver vserver -path /test

                Vserver: vserver
              File Path: /test
      File Inode Number: 64
         Security Style: ntfs
        Effective Style: ntfs
         DOS Attributes: 10
 DOS Attributes in Text: ----D---
Expanded Dos Attributes: -
           UNIX User Id: 0
          UNIX Group Id: 0
         UNIX Mode Bits: 777
 UNIX Mode Bits in Text: rwxrwxrwx
                   ACLs: NTFS Security Descriptor
                         Control:0x8014
                         Owner:BUILTIN\Administrators
                         Group:BUILTIN\Administrators
                         DACL - ACEs
                           ALLOW-DOMAIN\AD-USER-0x1f01ff-OI|CI
```

**Comment by mohanrajb9** [comment]
yes we observed this behavior, even though we set all apply_to true in create, but 2 acls are created.
this is documented in [validate_changes](https://docs.ansible.com/ansible/latest/collections/netapp/ontap/na_ontap_file_security_permissions_acl_module.html#parameter-validate_changes) for SLAG acls but I think file-directory acls also does the split.
we will check REST team regarding this split behavior and have a fix for this - tracked internally with DEVOPS-6001.
for now set exact match for apply_to when trying to delete the acl, thanks for reporting this.

**Comment by carchi8py** [comment]
This should be fix  22.6.0 bug also requires 

But also require the ontap patch from here.
https://mysupport.netapp.com/site/bugs-online/product/ONTAP/BURT/1563853

The fix is only in 9.13.1P3 and 9.14+

**Comment by PavGregor** [comment]
@carchi8py I still see this issue in FSxN with the following versions:
```
::> version
NetApp Release 9.13.1P5: Thu Nov 02 20:37:09 UTC 2023 
```
```
# ansible-galaxy collection list
Collection        Version
----------------- -------
community.general 7.2.1  
netapp.ontap      22.9.0
```
Just to clarify your reply, are you saying that I will need to apply a patch on top of the version released to AWS?

**Comment by carchi8py** [comment]
Your ontap version should be find, can you show me the output your seeing?

**Comment by PavGregor** [comment]
Sorry @carchi8py I should have added way more detail to my message. 

After a bit more testing, I think the "issue" is just the fact that when you create a new FSxN volume/cifs share you end up with two ACL entries for `Everyone` that require you to run two separate tasks to remove from the ACL.

Just for completeness, I create a new volume and share using these tasks:
```
- name: Create FSxN volume
  netapp.ontap.na_ontap_volume:
    state: present
    name: "{{ fsxn_share_name }}"
    junction_path: /{{ fsxn_share_name }}
    size: "{{ fsxn_share_size }}"
    size_unit: gb
    type: RW
    aggregate_name: aggr1
    volume_security_style: ntfs
    efficiency_policy: auto
    snapshot_policy: default
    tiering_policy: snapshot-only
    tiering_minimum_cooling_days: 2
    vserver: "{{ fsxn_vserver }}"
    hostname: "{{ fsxn_host }}"
    username: fsxadmin
    password: "{{ fsxn_password }}"
    validate_certs: false
    use_rest: always
    wait_for_completion: true

- name: Create CIFS share
  netapp.ontap.na_ontap_cifs:
    state: present
    name: "{{ fsxn_share_name }}"
    path: /{{ fsxn_share_name }}
    comment: AWS FSxN share created and managed by Ansible
    access_based_enumeration: false
    allow_unencrypted_access: false
    change_notify: true
    continuously_available: true
    home_directory: false
    oplocks: true
    show_snapshot: false
    hostname: "{{ fsxn_host }}"
    vserver: "{{ fsxn_vserver }}"
    username: fsxadmin
    password: "{{ fsxn_password }}"
    validate_certs: false
    use_rest: always
```
Which creates a share with these default ACL entries:
```
::> vserver security file-directory show -vserver vserver -path /test

                Vserver: vserver
              File Path: /test
      File Inode Number: 64
         Security Style: ntfs
        Effective Style: ntfs
         DOS Attributes: 10
 DOS Attributes in Text: ----D---
Expanded Dos Attributes: -
           UNIX User Id: 0
          UNIX Group Id: 0
         UNIX Mode Bits: 777
 UNIX Mode Bits in Text: rwxrwxrwx
                   ACLs: NTFS Security Descriptor
                         Control:0x8014
                         Owner:BUILTIN\Administrators
                         Group:BUILTIN\Administrators
                         DACL - ACEs
                           ALLOW-Everyone-0x1f01ff
                           ALLOW-Everyone-0x10000000-OI|CI|IO
```
So to remove the Everyone ACL I need to run two `netapp.ontap.na_ontap_file_security_permissions_acl` tasks, one with 
```
        acl_user: Everyone
        apply_to:
          this_folder: true
```
and a second with
```
        acl_user: Everyone
        apply_to:
          sub_folders: true
          files: true
```
It's a super minor issue, and seems to only affect this default Everyone entry, creating new user ACLs works as expected.
