### ISSUE TITLE
netapp.ontap.na_ontap_user allow for split roles for user

### ISSUE THREAD

**Issue by cordelster** [ansible-collections/netapp.ontap#157]
### Summary

netapp.ontap.na_ontap_user being item potent, does not allow for split roles of user. Where as user requires a custom role and service-processor access is not possible to accomplish. The service-processor application type only allows "admin" role because of device limitation where the device can not cope with implementing another role.   

The only workaround is to create a user with all applications under the role 'admin' then modify all applications except 'service-processor' in the cluster shell to use the intended role on each storage cluster.

The module needs to allow for modifying a users role per application at least. 

### Component Name

netapp.ontap.na_ontap_user

### Additional Information

```yaml (paste below)
      - hostname:                     "{{ cluster_name }}"
        name:                         'netapp-support'
        applications:                 service-processor
        authentication_method:        password
        lock_user:                    yes
        role_name:                    'admin'
        vserver:                      "{{ cluster_name }}"

      - hostname:                     "{{ cluster_name }}"
        name:                         'netapp-support'
        applications:                 ontapi,ssh,console,http
        authentication_method:        password
        lock_user:                    yes
        role_name:                    'netapp-service'
        vserver:                      "{{ cluster_name }}"
```
