### ISSUE TITLE
"system license show-status" not working for ONTAP 9.8 via na_ontap_rest_cli module

### ISSUE THREAD

**Issue by lorenzo-maffeo-SAP** [ansible-collections/netapp.ontap#160]
### Summary

When attempting to write a tast using na_ontap_rest_cli to call "system license show-status" agains a system running 9.8, an error is returned mentioning 'API not found'

### Component Name

na_ontap_rest_cli

### Ansible Version

```console
$ ansible --version
ansible 2.9.6
```

### ONTAP Collection Version

```console
$ ansible-galaxy collection list
netapp.ontap 21.15.1
```

### ONTAP Version

```console
:> version
NetApp Release 9.8P16: Fri Dec 02 02:05:05 UTC 2022
```

### Playbook

```console
tasks:
    - name: Get cluster information
      connection: local
      na_ontap_rest_cli:
        command: 'system/license/show-status'
        verb: GET
        params: {'status': 'partially-installed'}
      register: cluster_info
```

### Steps to Reproduce

Create a new playbook with a this single task and an inventory of 2 systems (one running 9.8 and one running 9.10)
```
  tasks:
    - name: Get cluster information
      connection: local
      na_ontap_rest_cli:
        command: 'system/license/show-status'
        verb: GET
        params: {'status': 'partially-installed'}
      register: cluster_info
```

### Expected Results

I expected the task to complete successfully since the command is available in ONTAP 9.8 and na_ontap_rest_cli module can be used with ONTAP 9.6+

### Actual Results

```console
fatal: [X.X.X.X]: FAILED! => {"changed": false, "msg": "Error: {'message': 'API not found', 'code': '3'}"}

---- 
ONTAP audit log shows
Sat Jun 17 08:12:29 2023  [redacted] :: GET /api/private/cli/system/license/show-status?status=partially-installed :: Pending
Sat Jun 17 08:12:29 2023  [redacted] GET /api/private/cli/system/license/show-status?status=partially-installed :: Error: invalid operation
```
