### ISSUE TITLE
na_ontap_cifs_local_user warns "[WARNING]: Module did not set no_log for set_password"

### ISSUE THREAD

**Issue by freedge** [ansible-collections/netapp.ontap#163]
### Summary

running a playbook containing this task:
```
  - name: cifs user
    na_ontap_cifs_local_user:
      state: present
      vserver: vs
      name: tata
      user_password: "{{ netapp_password }}"
      account_disabled: False
      full_name: Tata
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      use_rest: always
      https: true
      validate_certs: false
      description: a user account to access CIFS that can be used as default in mappings
    delegate_to: localhost
```
getting a warning:
```
[WARNING]: Module did not set no_log for set_password
```

### Component Name

na_ontap_cifs_local_user

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.4]
  config file = Xnetapp/ansible.cfg
  configured module search path = ['Xplugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = Xnetapp/myenv/lib/python3.10/site-packages/ansible
  ansible collection location = Xnetapp
  executable location = Xnetapp/myenv/bin/ansible
  python version = 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] (Xnetapp/myenv/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### ONTAP Collection Version

```console
$ ansible-galaxy collection list
Collection   Version                 
------------ -------                 
netapp.ontap 22.7.0
```

### ONTAP Version

```console
NetApp Release 9.13.1: Mon Jun 19 13:36:41 UTC 2023
```

### Playbook

```console
- name: cifs user
    na_ontap_cifs_local_user:
      state: present
      vserver: vs
      name: tata
      user_password: "{{ netapp_password }}"
      account_disabled: False
      full_name: Tata
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      use_rest: always
      https: true
      validate_certs: false
      description: a user account to access CIFS that can be used as default in mappings
    delegate_to: localhost
```

### Steps to Reproduce

```yaml (paste below)

```

### Expected Results

no warning

### Actual Results

```console
warning
```
