### ISSUE TITLE
na_ontap_broadcast_domain doesnt correctly modifying a broadcast domain's ports using REST

### ISSUE THREAD

**Issue by hashi825** [ansible-collections/netapp.ontap#210]
### Summary

When providing a broadcast domain that already contains existing ports and requires adding new ports, using REST will add ALL ports to the REST Patch request due to this statement which prevents actually only returning the ports to add
https://github.com/ansible-collections/netapp.ontap/blob/78486a16018f1c3f1d8cf133f6f4b0b39ba4bcb9/plugins/modules/na_ontap_broadcast_domain.py#L586-L599

https://github.com/ansible-collections/netapp.ontap/blob/78486a16018f1c3f1d8cf133f6f4b0b39ba4bcb9/plugins/modules/na_ontap_broadcast_domain.py#L466-L474

```ports_to_add``` provides the correct list of ports to add ```get_ports_rest``` then checks ```self.desired_ports``` which contains all ports found from the ```ports``` parameter of the module. This causes the module to send a patch request to `api/network/ethernet/ports` that essentially removes/readds ports that were already in the broadcast domain.

Removing the if statement seems to provide the desired behaviour.

### Component Name

na_ontap_broadcast_domain 

### Ansible Version

```console
$ ansible --version
ansible [core 2.15.0]
  config file = ##/ansible.cfg
  configured module search path = ['/home/##/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = ##/venv/lib64/python3.9/site-packages/ansible
  ansible collection location = ##
  executable location = ##/bin/ansible
  python version = 3.9.18 (main, Jan  4 2024, 00:00:00) [GCC 11.4.1 20230605 (Red Hat 11.4.1-2)] (##/venv/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True
```

### ONTAP Collection Version

```console
Collection            Version
--------------------- -------
ansible.posix         1.5.4  
community.general     7.2.0  
community.hashi_vault 4.2.0  
netapp.ontap          22.11.0
netbox.netbox         3.13.0
```

### ONTAP Version

```console
##::> version
NetApp Release 9.13.1P7: Wed Jan 24 16:17:54 UTC 2024
```

### Playbook

```console
- name: Modify broadcast domain
      gather_facts: false
      # Use local host for delegation
    connection: local
    hosts: all
    vars_prompt:
    - name: ontap_username
      prompt: Enter username for ontap_username
      private: false
    - name: ontap_password
      prompt: Enter password
      private: true
    vars:
        broadcast_domains:
          - name: cluster_mgmt
            mtu: 1500
            ports:
             - srva001ppa1:a0a-111
             - srva001ppa1:a1a-111
             - srva001ppa2:a0a-111
             - srva001ppa2:a1a-111
             - srva001ppa3:a0a-111
             - srva001ppa3:a1a-111
             - srva001ppa4:a0a-111
             - srva001ppa4:a1a-111
             - srva001ppa5:a0a-111
             - srva001ppa5:a1a-111
             - srva001ppa6:a0a-111
             - srva001ppa6:a1a-111
             - srva001ppa7:a0a-111
             - srva001ppa7:a1a-111
             - srva001ppa7:a2a-111
             - srva001ppa8:a0a-111
             - srva001ppa8:a1a-111
             - srva001ppa8:a2a-111

        tasks:
        - name: Create Broadcast Domains
          netapp.ontap.na_ontap_broadcast_domain:
            state: present
            name: "{{ item.name }}"
            mtu: "{{ item.mtu }}"
            ports: "{{ item.ports }}"
            ipspace: Default
            hostname: "{{ inventory_hostname }}"
            username: "{{ ontap_username }}"
            password: "{{ ontap_password }}"
            https: true
            validate_certs: false
          with_items: "{{ broadcast_domains }}"
          when: broadcast_domains != None
```

### Steps to Reproduce

```yaml (paste below)
- name: Create Broadcast Domains
  netapp.ontap.na_ontap_broadcast_domain:
    state: present
    name: "{{ item.name }}"
    mtu: "{{ item.mtu }}"
    ports: "{{ item.ports }}"
    ipspace: Default
    hostname: "{{ inventory_hostname }}"
    username: "{{ ontap_username }}"
    password: "{{ ontap_password }}"
    https: true
    validate_certs: "{{ ontap_validate_certs }}"
  with_items: "{{ broadcast_domains }}"
  when: broadcast_domains != None
```

### Expected Results

Expected that module will only add MISSING broadcast domain ports and not try and PATCH existing ports.

### Actual Results

```console
msg: 'calling: network/ethernet/ports/fbec63a4-af37-11eb-b786-00a098dc46e4: got {''message'': ''Port "###:a1a-111" cannot be used because it is currently the home port or current port of a LIF.'', ''code'': ''1377608''}.'
```
```
