### ISSUE TITLE
Provide cert and key as value instead of filepath

### ISSUE THREAD

**Issue by lvicainne** [ansible-collections/netapp.ontap#227]
### Summary

I'm using the `netapp.ontap` playbooks and would like to connect to the ONTAP clusters I manage over client certificate instead of password.
However, these credentials are saved in a vault (not in clear text locally in the filesystem where is run the playbook), and I need to provide these values.
Please, can you provide 2 additional parameters `key` and `cert` in addition to `key_filepath` and `cert_filepath`

Thank you

### Component Name

certificate

### Additional Information

```yaml (paste below)
  login: &login
    hostname: "{{ inventory_hostname }}.{{ dnsdomain }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    cert: "{{ vault.certvalue}}"
    key: "{{ vault.keyvalue }}"
    https: true
    validate_certs: "{{ validate_certs }}"
```
