### ISSUE TITLE
Extend na_ontap_security_config to specify server certificate to use

### ISSUE THREAD

**Issue by Jiawei0227** [ansible-collections/netapp.ontap#23]
### Summary

I am trying to translate the following command into an ansible module.
`ssl modify -vserver <vserver-name> -server-enabled true -client-enabled true -common-name <common-name> -serial <SN-from-trusted-CA-cert> -ca <cert-authority>`

And it seems the existing `na_ontap_security_config` cannot feed my need?

### Component Name

na_ontap_security_config

### Additional Information

```yaml (paste below)
- name: Modify SSL Security Config
  na_ontap_security_config:
    name: ssl
    vserver: xxx
    server_enabled: true
    client_enabled: true
    serial: xxx
    ca: xxx
    common_name: xxx
    <<: *ontap
```
