### ISSUE TITLE
Allow authentication with OAuth 2 Access Token

### ISSUE THREAD

**Issue by jduepmeier** [ansible-collections/netapp.ontap#231]
### Summary

The rest api for ontap now supports OAuth 2 authentification for the REST api.
Add a parameter to provide an access token for authentication.

See https://docs.netapp.com/us-en/ontap/authentication/overview-oauth2.html for additional informations.

Or https://docs.netapp.com/us-en/ontap/authentication/oauth2-rest-api.html#step-1-acquire-an-access-token with a curl example.

This should be supported in all modules that use the rest api.

### Component Name

modules.*

### Additional Information

```yaml (paste below)
- name: create or modify s3 user
  na_ontap_s3_users:
    state: present
    name: carchi8py
    vserver: ansibleSVM
    comment: not enabled
    hostname: "{{ netapp_hostname }}"
   # use token instead of username/password
    token: "{{ netapp_token }}"
    https: true
    validate_certs: false
    use_rest: always
```
