### ISSUE TITLE
interface_type should default to ip when subnet is provided

### ISSUE THREAD

**Issue by ansibleguy76** [ansible-collections/netapp.ontap#233]
### Summary

You introduced a mandatory property "interface_type", and you fall back to "ip" when address and netmask is provided, but forgot when subnet is provided, which is also "ip"
This brakes all playbooks that upgrade to the new version and where they use subnets.

### Component Name

na_ontap_interface

### Ansible Version

```console
$ ansible --version
latest
```

### ONTAP Collection Version

```console
$ ansible-galaxy collection list
21.13.0
```

### ONTAP Version

```console
sridharc-vsim34::> version
NetApp Release 9.7.0: Tue May 18 10:45:16 UTC 2021
9.14
```

### Playbook

```console
- name: "create lif {{ lif.name }}"               
    netapp.ontap.na_ontap_interface:
      state                : present
      subnet               : "{{ lif.subnet }}"
      interface_name       : "{{ lif.name }}"
#      interface_type       : ==> is now mandatory
      vserver              : "{{ svm.name }}"
      admin_status         : "up"
      home_node            : "{{ lif.node | default(omit) }}"
      home_port            : "{{ lif.port | default(omit) }}"
```

### Steps to Reproduce

```yaml (paste below)
 - name: "create lif with subnet"               
    netapp.ontap.na_ontap_interface:
      state                : present
      subnet               : "mysubnet"
      interface_name       : "data"
#      interface_type       : ==> is now mandatory
      vserver              : "svm1"
      admin_status         : "up"
      home_node            : "cluster1-01"
      home_port            : "e0c"
```

### Expected Results

upgrade to latest collection would not break playbook

### Actual Results

```console
Error: Missing one or more required parameters for creating interface: interface_type.'
```
