### ISSUE TITLE
na_ontap_user module overrides existing user configuration instead of modifying it

### ISSUE THREAD

**Issue by lorenzo-maffeo-SAP** [ansible-collections/netapp.ontap#237]
### Summary

We have a requirement to have a user able to log to the cluster nodes BMC and - from there - switch to system console and be allowed to run a subset of commands.
In ONTAP we achieve this by creating a custom role specifying which commands are allowed/disallowed, then we create a dedicate user for console access, as well as BMC access with admin role (since BMC does not support any other role):
`security login create -user-or-group-name <username> -role <custom_role> -application console -authentication-method password`
`security login create -user-or-group-name <username> -role admin -application service-processor -authentication-method password `

We are now looking to automate this through Ansible but it seems the na_ontap_user module, when used on a user with an existing name, just overrides the user configuration on second invocation rather than behaving like `security login create` from CLI.

### Component Name

user

### Ansible Version

```console
$ ansible --version
ansible [core 2.17.2]
  config file = None
  configured module search path = ['/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.11/site-packages/ansible
  ansible collection location = /runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.11.9 (main, Jul 18 2024, 00:00:00) [GCC 11.4.1 20231218 (Red Hat 11.4.1-3)] (/usr/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```

### ONTAP Collection Version

```console
$ ansible-galaxy collection list


# /usr/share/ansible/collections/ansible_collections
Collection         Version
------------------ -------
ansible.netcommon  7.0.0  
ansible.utils      5.1.0  
community.general  9.2.0  
netapp.ontap       22.11.0
netbox.netbox      3.19.1 
openstack.cloud    2.2.0
```

### ONTAP Version

```console
::> version
NetApp Release 9.14.1P7: Thu Aug 01 03:07:44 UTC 2024
```

### Playbook

```console
- name: Unlock custom user and set new password - console
      na_ontap_user:
        hostname: "{{ target_cluster }}"
        state: present
        name: custom_user
        applications: console
        authentication_method: password
        set_password: "{{ password }}"
        lock_user: false
        role_name: "custom_role"
        <<: *login

    - name: Unlock custom user - BMC
      na_ontap_user:
        hostname: "{{ target_cluster }}"
        state: present
        name: custom_user
        applications: service-processor
        authentication_method: password
        lock_user: false
        role_name: "admin"
        <<: *login
```

### Steps to Reproduce

```yaml (paste below)
    - name: Unlock custom user and set new password - console
      na_ontap_user:
        hostname: "{{ target_cluster }}"
        state: present
        name: custom_user
        applications: console
        authentication_method: password
        set_password: "{{ password }}"
        lock_user: false
        role_name: "custom_role"
        <<: *login

    - name: Unlock custom user - BMC
      na_ontap_user:
        hostname: "{{ target_cluster }}"
        state: present
        name: custom_user
        applications: service-processor
        authentication_method: password
        lock_user: false
        role_name: "admin"
        <<: *login
```

### Expected Results

I expect ONTAP to show user custom_user created for console access with custom_role role, and for service-processor access with admin role both sharing the same password

### Actual Results

```console
User will be created for console access with custom role, but will then be replaced by one with only service-processor access with admin role
```
