### ISSUE TITLE
Module na_ontap_aggregate ignores changing raid_type

### ISSUE THREAD

**Issue by nottohh** [ansible-collections/netapp.ontap#238]
### Summary

Changing the raid_type of an existing aggregate is ignored. Result of Ansible is OK changed=false

### Component Name

na_ontap_aggregate

### Ansible Version

```console
$ ansible --version
ansible [core 2.18.1]
  config file = /home/devops/ansible.cfg
  configured module search path = ['/home/devops/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/devops/.local/lib/python3.11/site-packages/ansible
  ansible collection location = /home/devops/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/devops/.local/bin/ansible
  python version = 3.11.10 (main, Nov  5 2024, 07:57:54) [GCC 8.5.0 20210514 (Red Hat 8.5.0-22)] (/usr/bin/python3.11)
  jinja version = 3.1.4
  libyaml = True
```

### ONTAP Collection Version

```console
$ ansible-galaxy collection list
Collection                               Version
---------------------------------------- -------
netapp.ontap                             22.13.0
```

### ONTAP Version

```console
na2213::> version
NetApp Release 9.14.1P1: Thu Feb 15 00:45:21 UTC 2024
```

### Playbook

```console
- name: "Create Aggregate aggr01-02 via REST"
      na_ontap_aggregate:
        <<: *na_login
        state: present
        name: "aggr1_{{ netapp_hostname }}_01"
        nodes: "{{ netapp_hostname }}-01"
        raid_type: raid_dp
        disk_count: 6
        service_state: online
```

### Steps to Reproduce

Changing the Value for raid_type from raid_dp to raid4 results in the following Ansible output:

ansible-playbook -i nas2213, playbook.yml -D

TASK [Create Aggregate aggr01-02 via REST] *********************************************************************************************
ok: [na2213]
```yaml (paste below)
   - name: "Create Aggregate aggr01-02 via REST"
      na_ontap_aggregate:
        <<: *na_login
        state: present
        name: "aggr1_{{ netapp_hostname }}_01"
        nodes: "{{ netapp_hostname }}-01"
        raid_type: raid4
        disk_count: 6
        service_state: online
```

### Expected Results

Expected result would be:

1. Ansible return Changed as result for the Task
2. Raidtype should have been changed after the script has run

### Actual Results

```console
Actual results are:

1. Ansible returns OK (changed: False)
2. Raidtype in ontap is still raid_dp
```
