### ISSUE TITLE
na_ontap_user not updating roles for all applications

### ISSUE THREAD

**Issue by Tombo-Netap** [ansible-collections/netapp.ontap#240]
### Summary

I'm trying to use the na_ontap_user module to update a role for all of a user applications
I've hit an edge case where the user has multiple roles only the first is checked then nothing is processed 

As an example :
user - http - admin
user - ssh - readonly 
 
If I try to update all of them to make it consistent i.e. make them both admin it will complete but not change anything as http admin is checked first

If the order is reversed the action completes as expected
e.g. 
user - http - readonly
user - ssh - admin

### Component Name

na_ontap_user module

### Ansible Version

```console
ansible --version
ansible [core 2.15.8]
  config file = /etc/ansible/ansible.cfg
  configured module search path = --removed--
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = --removed--
  executable location = /usr/local/bin/ansible
  python version = 3.9.19 (main, Aug 26 2024, 11:01:47) [GCC 8.5.0 20210514 (Red Hat 8.5.0-22)] (/usr/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

### ONTAP Collection Version

```console
$ ansible-galaxy collection list
Collection                    Version
----------------------------- -------
netapp.ontap                  22.4.1
```

### ONTAP Version

```console
version                                                                                                                     
NetApp Release 9.12.1P15: Wed Oct 09 08:30:57 UTC 2024
```

### Playbook

```console
- name: Update user access, 
    netapp.ontap.na_ontap_user:
      hostname: "{{ cluster_address }}"
      username: "{{ creds.username }}"
      password: "{{ creds.password }}"
      vserver: "{{ vserver }}"
      name: "{{ account }}"
      application_dicts: "{{ application_dicts }}"
      role_name: "{{ role }}"
```

### Steps to Reproduce

Create 2 user with different roles for different applications
Try to update both applications with the same role using the first role in the list

### Expected Results

both applications will have the same role for the user

### Actual Results

```console
The second does not update
```

**Comment by csahu9** [comment]
@Tombo-Netap Have you tried task similar to below?
```
    - name: Create a login method
      netapp.ontap.na_ontap_user:
        state: present
        name: test_user
        application_dicts:
          - application: http
            authentication_methods: password
          - application: ssh
            authentication_methods: password
        role_name: admin
        use_rest: always
      register: result
```
The module [na_ontap_user](https://docs.ansible.com/ansible/devel/collections/netapp/ontap/na_ontap_user_module.html#parameter-role_name) accepts a single role name that gets applied to all the given applications.
