### ISSUE TITLE
S3 user with specifc key and secret

### ISSUE THREAD

**Issue by JulienLejeuneCivadis** [ansible-collections/netapp.ontap#247]
### Summary

Use case : I would like to create an S3 user with a specific Access Key and secret.
Why ? I need to create the users with the same key and secret on multiple systems for a DRP scenario.
CLI command : ` object-store-server user regenerate-keys -user USERNAME -access-key KEY -secret-key SECRET` 
Proposal : add optional parameters like "new_key" and "new_secret" which would be used if "regenerate_keys"  is set to true.

### Component Name

na_ontap_s3_users

### Additional Information

```yaml (paste below)
- name: Create or modify s3 user on main server
  netapp.ontap.na_ontap_s3_users:
    state: present
    name: "{{ bucket_name }}"
    vserver: "{{ netapp_vserver }}"
    comment: "{{ bucket_comment }}"
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: true
    validate_certs: false
    use_rest: always
  register: netapp_created_user

- name: Create or modify s3 user on secundary server
  netapp.ontap.na_ontap_s3_users:
    state: present
    name: "{{ bucket_name }}"
    vserver: "{{ netapp_vserver }}"
    comment: "{{ bucket_comment }}"
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: true
    validate_certs: false
    use_rest: always
    regenerate_keys: true
    new_key: "{{ netapp_created_user.access_key }}"
    new_secret: "{{ netapp_created_user.secret_key }}"
```

**Comment by csahu9** [comment]
@JulienLejeuneCivadis `regenerate_keys` is used when `secret_key` and `access_key` need to be regenerated. [Swagger doc page](https://docs.netapp.com/us-en/ontap-restapi/ontap/swagger-ui/index.html#/Object-Store/s3_user_modify) for reference.
Example usage:
```
    - name: regenerate S3 user key
      na_ontap_s3_users:
        state: present
        name: test_user
        regenerate_keys: true # when using regenerate_keys, task will not be idempotent
```
Please note that `access_key` & `secret_key` can not be set in POST/PATCH.
