### ISSUE TITLE
"na_ontap_rest_cli" does not work as intended with "debug/kenv" command

### ISSUE THREAD

**Issue by lorenzo-maffeo-SAP** [ansible-collections/netapp.ontap#253]
### Summary

When using 'na_rest_ontap_cli' with 'debug/kenv', 'GET' calls work as intended but 'PATCH' calls fail silently.

Working task:
```
    - name: Check bootarg presence
      connection: local
      netapp.ontap.na_ontap_rest_cli:
        command: debug/kenv
        verb: GET
        params:
          variable: "{{ bootarg }}"
          fields: variable,value
        <<: *login
```

```
ok: [hostname] => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3.11"}, "changed": false, "msg": {**"num_records": 2**, "records":....
```

Non-working task:
```
    - name: Set bootarg
      connection: local
      netapp.ontap.na_ontap_rest_cli:
        command: debug/kenv
        verb: PATCH
        params:
          variable: "{{ bootarg }}"
          value: true
          persist: true
        <<: *login
```

```
changed: [hostname] => {"changed": true, "msg": {**"num_records": 0**}}
```

I can however change the bootarg just fine using cURL or the Ansible URI module
```
curl -u '********:$$$$$$$$' -X PATCH https://hostname/api/private/cli/debug/kenv\?variable\=..... -d '{ "value": "false" }'
{
  "num_records": 2
}%
```

```
    - name: Set bootarg
      connection: local
      ansible.builtin.uri:
        url: "https://{{inventory_hostname}}/api/private/cli/debug/kenv?variable={{bootarg}}"
        method: PATCH
        user: "{{ auto_user }}"
        password: "{{ auto_passwd }}"
        body_format: json
        body:
          value: true
```

```
ok: [hostname] => {"cache_control": "no-cache,no-store,must-revalidate", "changed": false, "connection": "close", "content_length": "22", "content_security_policy": "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; frame-ancestors: 'self'", "content_type": "application/hal+json", "cookies": {}, "cookies_string": "", "date": "Wed, 30 Apr 2025 06:21:39 GMT", "elapsed": 0, "json": **{"num_records": 2}**, "msg": "OK (22 bytes)", "redirected": false, "server": "libzapid-httpd", "status": 200, "url": "https://hostname/api/private/cli/debug/kenv?variable=....", "vary": "Origin", "x_content_type_options": "nosniff"}
```

### Component Name

na_ontap_rest_cli

### Ansible Version

```console
$ ansible --version
ansible [core 2.18.2]
  config file = None
  configured module search path = ['/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.11/site-packages/ansible
  ansible collection location = /runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.11.11 (main, Dec  3 2024, 00:00:00) [GCC 11.5.0 20240719 (Red Hat 11.5.0-2)] (/usr/bin/python3)
  jinja version = 3.1.5
  libyaml = True
```

### ONTAP Collection Version

```console
$ ansible-galaxy collection list
# /runner/.ansible/collections/ansible_collections
Collection            Version
--------------------- -------
netapp.ontap          22.14.0
```

### ONTAP Version

```console
::> version
NetApp Release 9.14.1P7: Thu Aug 01 03:07:44 UTC 2024
```

### Playbook

```console
- name: Set bootarg
      connection: local
      netapp.ontap.na_ontap_rest_cli:
        command: debug/kenv
        verb: PATCH
        params:
          variable: "{{ bootarg }}"
          value: true
          persist: true
        <<: *login
```

### Steps to Reproduce

```
    - name: Set bootarg
      connection: local
      netapp.ontap.na_ontap_rest_cli:
        command: debug/kenv
        verb: PATCH
        params:
          variable: "{{ bootarg }}"
          value: true
          persist: true
        <<: *login

```

### Expected Results

changed: [hostname] => {"changed": true, "msg": {"num_records": 2}}

### Actual Results

```console
changed: [hostname] => {"changed": true, "msg": {"num_records": 0}}
```
