### ISSUE TITLE
snapmirror absent fails

### ISSUE THREAD

**Issue by ansibleguy76** [ansible-collections/netapp.ontap#261]
### Summary

When doing a snapmirror absent, it fails on entry does not exist

### Component Name

na_ontap_snapmirror

### Ansible Version

```console
$ ansible --version
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/netappsrv/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /NetAppAutomation/netapp-env-311/lib/python3.11/site-packages/ansible
  ansible collection location = /home/netappsrv/.ansible/collections:/usr/share/ansible/collections
  executable location = /NetAppAutomation/netapp-env-311/bin/ansible
  python version = 3.11.9 (main, Mar 10 2025, 12:35:54) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] (/NetAppAutomation/netapp-env-311/bin/python3.11)
  jinja version = 3.1.6
  libyaml = True
```

### ONTAP Collection Version

```console
$ ansible-galaxy collection list
Collection                               Version
---------------------------------------- -------
netapp.ontap                             22.14.0
```

### ONTAP Version

```console
sridharc-vsim34::> version
NetApp Release 9.15.1P10: Thu Apr 17 14:04:43 UTC 2025
```

### Playbook

```console
- name: "Removing snapmirror [{{ snapmirror.source.svm.name + ':' + snapmirror.source.volume.name | default('') }}] -/-> [{{ snapmirror.destination.svm.name + ':' + snapmirror.destination.volume.name | default('') }}]"  
    netapp.ontap.na_ontap_snapmirror:
      state                       : absent
      source_endpoint             : 
        cluster                   : "{{ snapmirror.source.cluster.name }}"
        path                      : "{{ snapmirror.source.svm.name + ':' + snapmirror.source.volume.name | default('') }}"
      destination_endpoint        : 
        cluster                   : "{{ snapmirror.destination.cluster.name }}"
        path                      : "{{ snapmirror.destination.svm.name + ':' + snapmirror.destination.volume.name | default('') }}"
      <<: *auth
    delegate_to: localhost
    retries: 5
    delay: 10
```

### Steps to Reproduce

```yaml (paste below)
  - name: "Removing snapmirror [{{ snapmirror.source.svm.name + ':' + snapmirror.source.volume.name | default('') }}] -/-> [{{ snapmirror.destination.svm.name + ':' + snapmirror.destination.volume.name | default('') }}]"  
    netapp.ontap.na_ontap_snapmirror:
      state                       : absent
      source_endpoint             : 
        cluster                   : "{{ snapmirror.source.cluster.name }}"
        path                      : "{{ snapmirror.source.svm.name + ':' + snapmirror.source.volume.name | default('') }}"
      destination_endpoint        : 
        cluster                   : "{{ snapmirror.destination.cluster.name }}"
        path                      : "{{ snapmirror.destination.svm.name + ':' + snapmirror.destination.volume.name | default('') }}"
      <<: *auth
    delegate_to: localhost
```

### Expected Results

I would expect idempotency... snapmirror gone... I now need to add retries and delays.

Instead, this should be handled in the module instead.  

### Actual Results

```console
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NoneType: None
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error aborting SnapMirror: calling: snapmirror/relationships/5d7682d7-3b99-11f0-8afc-d039ea2ca214/transfers/83ffec69-3b99-11f0-8afc-d039ea2ca214: got {'message': \"entry doesn't exist\", 'code': '4', 'target': 'uuid'}."}
```
