### ISSUE TITLE
netapp.ontap.na_ontap_cifs_server parameter compatibility issues

### ISSUE THREAD

**Issue by erikgruetter** [ansible-collections/netapp.ontap#97]
### Summary

Hey there

We need to set the workgroup parameter in order for this to work in our environment. However, this parameter only works with ZAPI, and other set parameters like encrypt_dc_connection only work with REST. Any chance the workgroup parameter gets converted to REST or any other type of workaround available here? This basically now stops us from continuing, as both ZAPI and REST can't be used interchangeably in one step.

Best regards & many thanks for your help in advance
Erik

### Component Name

netapp.ontap.na_ontap_cifs_server

### Additional Information

```yaml (paste below)
  - name: join domain
    netapp.ontap.na_ontap_cifs_server:
      state: present
      name: XXX
      vserver: XXX
      service_state: started
      domain: example.com
      admin_user_name: adminusername
      encrypt_dc_connection: yes
      aes_netlogon_enabled: yes
      kdc_encryption: yes
      admin_password: "{{netapp_password}}"
      hostname: hostname
      username: adminusername
      password: XXX
      validate_certs: false
      workgroup: XXX
```
